
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jan 12 13:43:13 CET 2018
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DOSPUNTOS = 43;
  public static final int CONST = 10;
  public static final int POR = 3;
  public static final int CCOR = 40;
  public static final int INTEGER = 17;
  public static final int WRITEINT = 32;
  public static final int ARRAY = 7;
  public static final int FOR = 15;
  public static final int ACOR = 39;
  public static final int NOT = 19;
  public static final int AND = 6;
  public static final int IGUAL = 5;
  public static final int RECORD = 23;
  public static final int TYPE = 28;
  public static final int OR = 21;
  public static final int BEGIN = 8;
  public static final int WRITELN = 33;
  public static final int IF = 16;
  public static final int ID = 34;
  public static final int APAREN = 37;
  public static final int OF = 20;
  public static final int BOOLEAN = 9;
  public static final int EOF = 0;
  public static final int RETURN = 24;
  public static final int CPAREN = 38;
  public static final int TRUE = 27;
  public static final int error = 1;
  public static final int COMA = 41;
  public static final int MENOS = 2;
  public static final int PCOMA = 42;
  public static final int MAYOR = 4;
  public static final int PUNTOS = 44;
  public static final int MODULE = 18;
  public static final int ELSE = 12;
  public static final int PUNTO = 45;
  public static final int CDIGITO = 35;
  public static final int CCADENA = 36;
  public static final int WRITESTRING = 31;
  public static final int TO = 26;
  public static final int WHILE = 30;
  public static final int THEN = 25;
  public static final int END = 13;
  public static final int FALSE = 14;
  public static final int VAR = 29;
  public static final int PROCEDURE = 22;
  public static final int DO = 11;
}

